export const STAGE_NAME = "STAGE_MAIN";
export const ELEMENT_SELECTABLE_BY_RECTANGLE_NAME = "SELECTABLE_BY_GROUP";
export const ELEMENT_SELECTABLE_BY_CLICK_NAME = "SELECTABLE_BY_CLICK";
export const ELEMENT_ARROW = "ARROW";
export const ELEMENT_ARROW_CIRCLE = "ARROW_CIRCLE";
